name: MurderMystery
main: io.github.mebsic.murdermystery.MurderMysteryPlugin
version: 0.1
depend: [Hycopy]
softdepend: [Citizens]
commands:
  chance:
    usage: /chance
  start:
    usage: /start
  token:
    usage: /token <player> <amount>
  wins:
    usage: /wins <player> <amount>
  image:
    usage: /image <URL>
  clearimage:
    usage: /clearimage
  togglehints:
    usage: /togglehints
  whoismurderer:
    usage: /whoismurderer
  whoisdetective:
    usage: /whoisdetective
  getrole:
    usage: /getrole <player>
